CREATE TABLE IF NOT EXISTS schedule_flight  (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure_iata VARCHAR (10),
    arrival_iata VARCHAR (10),
    distance INTEGER,
    min_value FLOAT,
    aircraft_model VARCHAR (50),
    endpoint_url VARCHAR (1000),
    create_at DATE DEFAULT CURRENT_DATE
)
